version: '3.9'
services:
  backend:
    build: ./app
    ports:
      - '3001:3001'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 60s
      retries: 5
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mongoadmin" ,"ping", "-h", "localhost"]
      timeout: 60s
      retries: 5

      