version: '3.9'

services:

  backend:
    build: .
    container_name: backend
    ports:
      - 3001:3001
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=27012000
    links:
      - db
    depends_on:
      - db
    restart: 'always'

  db:
    image: mongo:4.4.6
    container_name: db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=27012000
    restart: 'always'

      