on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verification of Git Operation
        uses: actions/checkout@v2

      - name: Install node with version
        uses: actions/setup-node@v1
        with:
        node-version: 14

      - name: Installing the dependencies
        run: npm install

      - name: Running lint to check for errors
        run: npx eslint .

